apiVersion: v1
kind: Service
metadata:
  name: chisel-remote-support-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: chisel-remote-support-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chisel-remote-support-web
spec:
  selector:
    matchLabels:
      app: chisel-remote-support-web
  replicas: 1
  template:
    metadata:
      labels:
        app: chisel-remote-support-web
    spec:
      containers:
      - name: chisel-remote-support-web
        image: AWS_ACC_NUM.dkr.ecr.us-west-2.amazonaws.com/remote-support-web:v1
        ports:
        - containerPort: 80