apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: logstash.tf-support.com
  namespace: default
spec:
  secretName: logstash-tf-support-tls
  duration: 8760h # 365d
  renewBefore: 720h # 30d
  commonName: logstash.tf-support.com
  dnsNames:
  - logstash.tf-support.com
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer