apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nmr.tf-customer.local
  namespace: default
spec:
  secretName: nmr-tf-customer-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: nmr.tf-customer.local
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs8
  usages:
    - server auth
    - client auth
  dnsNames:
  - nmr.tf-customer.com
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io